ALTER TABLE businesses
    ADD COLUMN phone VARCHAR(20),
    ADD COLUMN instagram_url VARCHAR(255),
    ADD COLUMN tiktok_url VARCHAR(255),
    ADD COLUMN has_parking BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN allows_pets BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN has_wifi BOOLEAN NOT NULL DEFAULT FALSE;