ALTER TABLE businesses
    ALTER COLUMN name DROP NOT NULL,
ALTER COLUMN address DROP NOT NULL,
    ALTER COLUMN city DROP NOT NULL,
    ALTER COLUMN state DROP NOT NULL,
    ALTER COLUMN latitude DROP NOT NULL,
    ALTER COLUMN longitude DROP NOT NULL;

ALTER TABLE businesses
    ADD COLUMN onboarding_completed BOOLEAN NOT NULL DEFAULT FALSE;