ALTER TYPE business_category ADD VALUE IF NOT EXISTS 'HAIRDRESSER';
ALTER TYPE business_category ADD VALUE IF NOT EXISTS 'WELLNESS';
ALTER TYPE business_category ADD VALUE IF NOT EXISTS 'SKINCARE';
ALTER TYPE business_category ADD VALUE IF NOT EXISTS 'EYEBROWS_LASHES';
ALTER TYPE business_category ADD VALUE IF NOT EXISTS 'MAKEUP';
ALTER TYPE business_category ADD VALUE IF NOT EXISTS 'OTHER';